2020-04-25T10:34:23.1829880+03:00 [WRN] (Sporty.Infra.Data.Accessor.RabbitMQ.Implementations.RabbitMQPersistentConnection) RabbitMQ Client could not connect after 2.0 sec, Error message=None of the specified endpoints were reachable
2020-04-25T10:34:44.6587985+03:00 [WRN] (Sporty.Infra.Data.Accessor.RabbitMQ.Implementations.RabbitMQPersistentConnection) RabbitMQ Client could not connect after 4.0 sec, Error message=None of the specified endpoints were reachable
2020-04-25T10:34:56.2184113+03:00 [WRN] (Sporty.Infra.Data.Accessor.RabbitMQ.Implementations.RabbitMQPersistentConnection) RabbitMQ Client could not connect after 8.0 sec, Error message=None of the specified endpoints were reachable
2020-04-25T10:35:10.3600143+03:00 [WRN] (Sporty.Infra.Data.Accessor.RabbitMQ.Implementations.RabbitMQPersistentConnection) RabbitMQ Client could not connect after 16.0 sec, Error message=None of the specified endpoints were reachable
2020-04-25T10:35:33.1824400+03:00 [WRN] (Sporty.Infra.Data.Accessor.RabbitMQ.Implementations.RabbitMQPersistentConnection) RabbitMQ Client could not connect after 32.0 sec, Error message=None of the specified endpoints were reachable
2020-04-25T11:28:50.8776484+03:00 [ERR] (AutoWrapper.AutoWrapperMiddleware) [500]: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/nosqldata:27017" }", EndPoint: "Unspecified/nosqldata:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ResolveEndPointsAsync(EndPoint initial)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastUpdateTimestamp: "2020-04-25T08:28:40.3908884Z" }] }.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Sporty.Services.Groups.Manager.GroupManager.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[Sporty.Infra.Data.Accessor.Mongo.Models.MongoConfiguration], Microsoft.Extensions.Logging.ILogger`1[Sporty.Services.Groups.Manager.GroupManager])' on type 'GroupManager'.
 ---> System.TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/nosqldata:27017" }", EndPoint: "Unspecified/nosqldata:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ResolveEndPointsAsync(EndPoint initial)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastUpdateTimestamp: "2020-04-25T08:28:40.3908884Z" }] }.
   at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChanged(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.Cluster.SelectServer(IServerSelector selector, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelection(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupported(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.StartImplicitSession(CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.StartImplicitSession(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ListCollections(ListCollectionsOptions options, CancellationToken cancellationToken)
   at Sporty.Infra.Data.Accessor.Mongo.Repository.MongoRepository`2.IsCollectionExists(String collectionName) in C:\projects\eng\sporty\SportyGitHub\dev\backend\Infra\Sporty.Infra.Data.Accessor\Mongo\Repository\MongoRepository.cs:line 42
   at Sporty.Infra.Data.Accessor.Mongo.Repository.MongoRepository`2.Init(String collectionName) in C:\projects\eng\sporty\SportyGitHub\dev\backend\Infra\Sporty.Infra.Data.Accessor\Mongo\Repository\MongoRepository.cs:line 29
   at Sporty.Services.Groups.Manager.GroupManager..ctor(IOptions`1 options, ILogger`1 logger) in C:\projects\eng\sporty\SportyGitHub\dev\backend\Services\Sporty.Services.Groups\Manager\GroupManager.cs:line 26
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context)
   at AutoWrapper.Base.WrapperBase.InvokeAsyncBase(HttpContext context, AutoWrapperMembers awm)
2020-04-25T15:41:02.5122252+03:00 [ERR] (AutoWrapper.AutoWrapperMiddleware) [404]: https://httpstatuses.com/404 : Group with Id: a1212c1b-5856-3b48-9201-f39d724372a0 does not exist.
Type    : https://httpstatuses.com/404
Title   : Group with Id: a1212c1b-5856-3b48-9201-f39d724372a0 does not exist.
Status  : 404
Detail  : 
Instance: /api/v1/Groups/a1212c1b-5856-3b48-9201-f39d724372a0/Members/a1212c1b-5856-3b48-9201-f39d724372a0

2020-04-25T15:42:07.0819038+03:00 [ERR] (AutoWrapper.AutoWrapperMiddleware) [404]: https://httpstatuses.com/404 : Member with Id: a1212c1b-5856-3b48-9201-f39d724372a1 does not belong to group with id: 1b2c21a1-5658-483b-9201-f39d724372a0.
Type    : https://httpstatuses.com/404
Title   : Member with Id: a1212c1b-5856-3b48-9201-f39d724372a1 does not belong to group with id: 1b2c21a1-5658-483b-9201-f39d724372a0.
Status  : 404
Detail  : 
Instance: /api/v1/Groups/1b2c21a1-5658-483b-9201-f39d724372a0/Members/a1212c1b-5856-3b48-9201-f39d724372a1

2020-04-25T15:56:15.9510361+03:00 [ERR] (AutoWrapper.AutoWrapperMiddleware) [404]: https://httpstatuses.com/404 : Member with Id: a1212c1b-5856-3b48-9201-f39d724372a1 does not exist.
Type    : https://httpstatuses.com/404
Title   : Member with Id: a1212c1b-5856-3b48-9201-f39d724372a1 does not exist.
Status  : 404
Detail  : 
Instance: /api/v1/Groups/1b2c21a1-5658-483b-9201-f39d724372a0/Members/a1212c1b-5856-3b48-9201-f39d724372a1

2020-04-25T15:58:07.4370099+03:00 [ERR] (AutoWrapper.AutoWrapperMiddleware) [404]: https://httpstatuses.com/404 : Member with Id: a1212c1b-5856-3b48-9201-f39d724372a1 does not exist.
Type    : https://httpstatuses.com/404
Title   : Member with Id: a1212c1b-5856-3b48-9201-f39d724372a1 does not exist.
Status  : 404
Detail  : 
Instance: /api/v1/Groups/1b2c21a1-5658-483b-9201-f39d724372a0/Members/a1212c1b-5856-3b48-9201-f39d724372a1

2020-04-25T16:01:04.3027922+03:00 [ERR] (AutoWrapper.AutoWrapperMiddleware) [404]: https://httpstatuses.com/404 : Member with Id: a1212c1b-5856-3b48-9201-f39d724372a1 does not exist.
Type    : https://httpstatuses.com/404
Title   : Member with Id: a1212c1b-5856-3b48-9201-f39d724372a1 does not exist.
Status  : 404
Detail  : 
Instance: /api/v1/Groups/1b2c21a1-5658-483b-9201-f39d724372a0/Members/a1212c1b-5856-3b48-9201-f39d724372a1

